backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

# app urls
urlpatterns += [
    path('', include('main.urls', namespace='main')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import CreatePDFView, PDFDetailView

app_name = 'main'

urlpatterns = [
    path('', CreatePDFView.as_view(), name='create-pdf'),
    path('<int:pk>/details/', PDFDetailView.as_view(), name='pdf-detail')
]

main/models.py
from django.db import models
from django.urls import reverse


AUDIO_VOICES = (
    ('0', 'Male'),
    ('1', 'Female')
)


class PDFAudio(models.Model):
    text = models.TextField()
    pdf = models.FileField(upload_to='pdfs')
    audio_file = models.FileField(upload_to='recs',
        blank=True, null=True)
    audio_rate = models.IntegerField(blank=True, null=True,
        default=125)
    volume_level = models.DecimalField(
        decimal_places=1, max_digits=2,
        blank=True, null=True, default=1.0)
    audio_voice = models.CharField(max_length=1, choices=AUDIO_VOICES,
        default=0)

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.pdf.name

    def get_absolute_url(self):
        return reverse('main:pdf-detail', kwargs={
            'pk': self.pk})

main/views.py
import os

from django.views.generic import CreateView, DetailView
from django.http import HttpResponseRedirect
from django.core.files import File

from .models import PDFAudio
from .utils import convert_pdf_to_audio


class CreatePDFView(CreateView):
    model = PDFAudio
    fields = ('pdf', 'audio_rate', 'volume_level',
        'audio_voice')

    def form_valid(self, form):
        # access inmemory file using - form.cleaned_data.get('file').read() / .file.getvalue()
        # tensorflow needs a path to file, create a temp file and use its path
        self.object = form.save()
        file_path, text = convert_pdf_to_audio(self.object)
        self.object.text = text.strip()
        with open(file_path, 'rb') as fi:
            self.object.audio_file = File(fi, name=os.path.basename(fi.name))
            self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class PDFDetailView(DetailView):
    model = PDFAudio
    queryset = PDFAudio.objects.all()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <!-- MDB icon -->
  <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  {% block head %}

  {% endblock head %}
</head>
<body>

  <!-- Start your project here
  <div style="height: 100vh">
    <div class="flex-center flex-column">
      <h1 class="text-hide animated fadeIn mb-4" style="background-image: url('https://mdbootstrap.com/img/logo/mdb-transparent-250px.png'); width: 250px; height: 90px;">MDBootstrap</h1>
      <h5 class="animated fadeIn mb-3">Thank you for using our product. We're glad you're with us.</h5>
      <p class="animated fadeIn text-muted">MDB Team</p>
    </div>
  </div>
    End your project here-->

  {% include "navbar.html" %}

  {% block content %}

  {% endblock content %}

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>

  {% block scripts %}

  {% endblock scripts %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design for Bootstrap</title>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="css/mdb.min.css">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="css/style.css">
</head>
<body>

  <!-- Start your project here-->  
  <div style="height: 100vh">
    <div class="flex-center flex-column">
      <h1 class="text-hide animated fadeIn mb-4" style="background-image: url('https://mdbootstrap.com/img/logo/mdb-transparent-250px.png'); width: 250px; height: 90px;">MDBootstrap</h1>
      <h5 class="animated fadeIn mb-3">Thank you for using our product. We're glad you're with us.</h5>
      <p class="animated fadeIn text-muted">MDB Team</p>
    </div>
  </div>
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="js/jquery.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>

</body>
</html>

templates/main/pdfaudio_detail.html
{% extends "base.html" %}

{% block title %}
  PDF To Audio Details
{% endblock title %}

{% block head %}

<style>
  textarea {
    overflow-y: scroll !important;
    height: 100px;
    resize: none
  }
</style>

{% endblock head %}

{% block content %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="md-form mb-4">
        <textarea id="form7" class="md-textarea form-control" rows="10">{{ object.text }}</textarea>
        <label for="form7">PDF To Text</label>
      </div>
      <div>
        <audio src="{{ object.audio_file.url }}" controls="controls"></audio>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/main/pdfaudio_form.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  PDF To Audio File Converter
{% endblock title %}

{% block head %}

{% endblock head %}

{% block content %}

  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <form action="." method="post" enctype="multipart/form-data" class="mt-5">
          {% csrf_token %}
          {{ form.errors }}
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <span class="input-group-text" id="id_pdf">Upload</span>
              {% if form.file.errors %}
                <div class="text-danger">
                  {% for error in form.file.errors %}
                    <p>{{ error }}</p>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
            <div class="custom-file">
              <input name="pdf" type="file" class="custom-file-input" id="id_pdf"
                aria-describedby="id_pdf" accept="application/pdf">
              <label class="custom-file-label" for="id_pdf">Choose PDF</label>
            </div>
          </div>
          {% if form.pdf.errors %}
            <div class="text-danger">
              {% for error in form.pdf.errors %}
                <p>{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}
          <div class="md-form">
            <input value="{{ form.audio_rate.value }}" name="audio_rate" type="text" id="id_audio_rate" class="form-control">
            <label for="id_audio_rate">Audio Rate (Optional)</label>
            {% if form.audio_rate.errors %}
              <div class="text-danger">
                {% for error in form.audio_rate.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <div class="md-form">
            <input value="{{ form.volume_level.value }}" name="volume_level" type="text" id="id_volume_level" class="form-control">
            <label for="id_volume_level">Volume Level (Optional)</label>
            {% if form.audio_rate.errors %}
              <div class="text-danger">
                {% for error in form.audio_rate.errors %}
                  <p>{{ error }}</p>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          <select value="{{ form.audio_voice.value }}" name="audio_voice" id="id_audio_voice" class="browser-default custom-select">
            <option selected="" value="0">Male</option>
            <option value="1">Female</option>
          </select>
          <div class="mt-3">
            <button class="btn btn-success">Convert to Audio File</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

{% block scripts %}

<script src="{% static 'js/scripts/main.js' %}" type="text/javascript"></script>

{% endblock scripts %}

templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">
  <!-- <div class="container"> -->
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">PDF To Audio</a>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
      aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

      <!-- Links -->
      <ul class="navbar-nav ml-lg-5 mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:create-pdf' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>

        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>

      </ul>
      <!-- Links -->
    </div>
    <!-- Collapsible content -->
  <!-- </div> -->
</nav>
<!--/.Navbar-->